### ISSUE TITLE
Adding some documentation and code/vs-solution.

### ISSUE THREAD

**Issue by MGNute** [pygobject/cairo-win-build#8]
I saw your post on the other repo this morning and appreciate your pointing this one out. I'm curious what the motivation is for this and if you're actively adding to it? I'd love to have something that kept a windows-build refreshed and public and made it easy to build from source for someone who needed to.  The first two things that come to mind that would be good to add are (a) some additional documentation and maybe a walkthrough or something like that, and (b) some kind of script or visual-studio project/sln that could be used to quickly generate a new build. Happy to try and contribute some of that but it might be good to get on the same page about the goals. Happy to chat about it if that'd be best.

**Comment by MGNute** [comment]
As I go through this repo a bit more I realize a lot of the stuff needed to produce the build independently is actually in there, although I'm not familiar with the tools like subprojects. But some documentation about how to implement them could be useful.

**Comment by lazka** [comment]
Sure, I'll try to expand the README a bit.

This is actively used/maintained for building [pycairo](https://github.com/pygobject/pycairo) packages.

**Comment by MGNute** [comment]
The pycairo library is amazingly stable considering how hard it is to get your hands on a fresh cairo.dll. But that's good to hear. If you don't have time I'd be happy to write up docs, I just have to learn how it all works first lol. This is the first time I've heard the word "subproject" actually.

**Comment by lazka** [comment]
I've extended the README a bit. Let me know what you think.
